[build]
  # Frontend build settings
  publish = "build"
  command = "npm run build"

[[redirects]]
  # SPA fallback for React Router
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Node version for build
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions for serverless backend (if needed)
[functions]
  directory = "netlify/functions"